server:
  http:
    port: 8089
  port: 8443
  ssl:
    key-store: classpath:https.p12
    key-alias: bigdata
    key-store-password: 123456
    enabled: true
    key-store-type: JKS
  #tomcat:
  #  uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://10.69.202.101:3306/iotbj1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    multipart:
      max-file-size: 10000Mb
      max-request-size: 10000Mb
mybatis:
   mapperLocations: classpath:/mapper/*.xml


mqtt:
  host: tcp://loraserver.bdiot.tech
  clientid: mqtt_subscribe_
  username: admin
  password: admin
  topic: application/3/device/347b686900420037/rx
  timeout: 1500

#是否调用海康接口
hikEnable: true

#本地返回地址
localhostUri: http://10.69.202.101:8089

algorithm:
  push: 10.69.212.11:8089 #视频流地址
  url: http://10.69.212.11:8087 #算法后端URL
  resultUrl: http://10.69.202.101:8189/algorithmresult #算法后端结果发送URL
algorithm_face:
  face_register: http://10.69.212.11:8800/api/v1.0/face_register
iot:
  url: https://10.69.206.70:10443/restapi/iot/iotinfomgr #北向服务URL
  apikey: KWrgSTHd36CHMa3wlNSECTkckMntDK6U #北向服务APIKEY

oa:
  baseUrl: http://10.69.206.48      # http://10.69.206.23
  appId: Potc5cAAaXVlQASwU233NraEEo5KXAat
  tenantId: lfdc
  secret: 79246cdd-dfa2-47ad-9252-289b78b8947e
  rootMenu: 6030ac57-bbef-4ba0-8793-00a77907cd26

app-version:


